# Generated by Django 3.0.3 on 2021-04-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210411_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='remark',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
